name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details about what you'd like to see added.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: Describe the problem or use case...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've thought about...

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which part of the application would this feature affect?
      options:
        - Not sure
        - SQL Editor/Query Execution
        - Database Explorer
        - RBAC/User Management
        - Metrics Dashboard
        - Query History/Logs
        - Data Export/Import
        - Table Management
        - Authentication
        - UI/UX
        - Performance
        - Security
        - Other

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: If applicable, provide examples of similar features in other tools or mockups
      placeholder: Links to examples, screenshots, or mockups...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: Add any other context about the feature request here...
