{{- if .Values.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chouse-ui.fullname" . }}-config
  labels:
    {{- include "chouse-ui.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
{{- end }}
